### ISSUE TITLE
Hotkey Support 

### ISSUE THREAD

**Issue by Wgis** [JustMrPhoenix/Noir#1]
Can you add F3 hotkey to fast open Run menu?

**Comment by JustMrPhoenix** [comment]
Sadly none of the function keys are actually available to be used inside gmod chromium.
In addition to that the hotkey system used in this project is fully dependent on chromium as it likes to suppress keyboard events.
Instead I introduced a "Quick Run" function with a hotkey `Ctrl + E`. It will run the file on the last used target or on self by default. Those changes are available in [e6f66d7](https://github.com/JustMrPhoenix/Noir/commit/e6f66d75bc5cf11db6c93a14ea7f91f0c7cc7d42)

**Comment by Wgis** [comment]
ohh, i mean something like in Gcompute...)
